# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd5db8c85d0ae69deec8d56593ec1d6feda34a9ade71775e2280ebf31348ef248495bc20bc45c92e90e36775ce3b825ba764fcf3a515003604056b085ecc1f15

test:
  secret_key_base: 41c96b80c267727ffd5cc2e67e9ccc93ece0e3ae45c8d0b811dbfaccea9e94e46e9dfe6a0f38737e4407236cbdd6f0f126819202db516e7665927b53441177cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
